/*
 * Copyright Debezium Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package io.debezium.connector.jdbc.dialect.snowflake;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Types;
import java.util.HashMap;
import java.util.Map;

import org.apache.kafka.connect.data.Schema;
import org.apache.kafka.connect.data.SchemaBuilder;
import org.hibernate.SessionFactory;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import io.debezium.bindings.kafka.KafkaDebeziumSinkRecord;
import io.debezium.connector.jdbc.JdbcKafkaSinkRecord;
import io.debezium.connector.jdbc.JdbcSinkConnectorConfig;
import io.debezium.connector.jdbc.JdbcSinkRecord;
import io.debezium.connector.jdbc.dialect.DatabaseDialect;
import io.debezium.connector.jdbc.hibernate.dialect.snowflake.SnowflakeDialect;
import io.debezium.connector.jdbc.relational.TableDescriptor;
import io.debezium.connector.jdbc.util.SinkRecordBuilder;
import io.debezium.sink.column.ColumnDescriptor;

/**
 * Unit tests for the SQL statements generated by {@link SnowflakeDatabaseDialect}, using an
 * offline-booted Hibernate {@link SessionFactory} so no Snowflake connection is required.
 */
@Tag("UnitTests")
public class SnowflakeDatabaseDialectTest {

    private static SessionFactory sessionFactory;
    private static JdbcSinkConnectorConfig config;
    private static DatabaseDialect dialect;

    @BeforeAll
    static void boot() {
        final Map<String, String> props = new HashMap<>();
        props.put(JdbcSinkConnectorConfig.CONNECTION_PROVIDER,
                "org.hibernate.engine.jdbc.connections.internal.UserSuppliedConnectionProviderImpl");
        props.put(JdbcSinkConnectorConfig.CONNECTION_URL, "jdbc:snowflake://unit-test");
        props.put(JdbcSinkConnectorConfig.CONNECTION_USER, "unit");
        props.put(JdbcSinkConnectorConfig.CONNECTION_PASSWORD, "unit");
        props.put(JdbcSinkConnectorConfig.INSERT_MODE, "upsert");
        props.put(JdbcSinkConnectorConfig.PRIMARY_KEY_MODE, "record_key");
        props.put("hibernate.dialect", SnowflakeDialect.class.getName());
        props.put("hibernate.boot.allow_jdbc_metadata_access", "false");

        config = new JdbcSinkConnectorConfig(props);
        sessionFactory = config.getHibernateConfiguration().buildSessionFactory();
        dialect = new SnowflakeDatabaseDialect.SnowflakeDatabaseDialectProvider().instantiate(config, sessionFactory);
    }

    @AfterAll
    static void shutdown() {
        if (sessionFactory != null) {
            sessionFactory.close();
        }
    }

    @Test
    public void testUpsertWithOnlyKeyFieldsOmitsWhenMatchedClause() {
        final String sql = dialect.getUpsertStatement(allKeyTable(), allKeyRecord());

        assertThat(sql).doesNotContain("WHEN MATCHED");
        assertThat(sql).doesNotContain("SET  WHEN");
        assertThat(sql).isEqualTo("MERGE INTO TenantClients AS T USING "
                + "(SELECT TENANT_ID AS TENANT_ID,CLIENT_ID AS CLIENT_ID FROM (VALUES (?,?)) AS TBL (TENANT_ID,CLIENT_ID)) "
                + "AS S (TENANT_ID,CLIENT_ID) ON T.TENANT_ID=S.TENANT_ID AND T.CLIENT_ID=S.CLIENT_ID "
                + "WHEN NOT MATCHED THEN INSERT (TENANT_ID,CLIENT_ID) VALUES (S.TENANT_ID,S.CLIENT_ID)");
    }

    @Test
    public void testUpsertWithNonKeyFieldsRetainsWhenMatchedClause() {
        final String sql = dialect.getUpsertStatement(customersTable(), customerRecord());

        assertThat(sql).contains(" WHEN MATCHED THEN UPDATE SET T.NAME=S.NAME ");
        assertThat(sql).contains(" ON T.ID=S.ID ");
        assertThat(sql).contains(" WHEN NOT MATCHED THEN INSERT (ID,NAME) VALUES (S.ID,S.NAME)");
    }

    private static JdbcSinkRecord allKeyRecord() {
        final Schema keySchema = SchemaBuilder.struct()
                .field("tenant_id", Schema.STRING_SCHEMA)
                .field("client_id", Schema.STRING_SCHEMA)
                .build();
        return toJdbcRecord(SinkRecordBuilder.create()
                .name("TenantClients")
                .topic("TenantClients")
                .offset(1)
                .keySchema(keySchema)
                .recordSchema(keySchema)
                .sourceSchema(sourceSchema())
                .key("tenant_id", "t1")
                .key("client_id", "c1")
                .after("tenant_id", "t1")
                .after("client_id", "c1")
                .build());
    }

    private static TableDescriptor allKeyTable() {
        return TableDescriptor.builder()
                .tableName("TenantClients")
                .type("TABLE")
                .column(varcharColumn("TENANT_ID", true))
                .column(varcharColumn("CLIENT_ID", true))
                .keyColumn("TENANT_ID")
                .keyColumn("CLIENT_ID")
                .build();
    }

    private static JdbcSinkRecord customerRecord() {
        final Schema keySchema = SchemaBuilder.struct()
                .field("id", Schema.STRING_SCHEMA)
                .build();
        final Schema recordSchema = SchemaBuilder.struct()
                .field("id", Schema.STRING_SCHEMA)
                .field("name", Schema.OPTIONAL_STRING_SCHEMA)
                .build();
        return toJdbcRecord(SinkRecordBuilder.create()
                .name("Customers")
                .topic("Customers")
                .offset(1)
                .keySchema(keySchema)
                .recordSchema(recordSchema)
                .sourceSchema(sourceSchema())
                .key("id", "1")
                .after("id", "1")
                .after("name", "Jane")
                .build());
    }

    private static TableDescriptor customersTable() {
        return TableDescriptor.builder()
                .tableName("Customers")
                .type("TABLE")
                .column(varcharColumn("ID", true))
                .column(varcharColumn("NAME", false))
                .keyColumn("ID")
                .build();
    }

    private static Schema sourceSchema() {
        return SchemaBuilder.struct()
                .field("db", Schema.OPTIONAL_STRING_SCHEMA)
                .build();
    }

    private static ColumnDescriptor varcharColumn(String name, boolean primaryKey) {
        return ColumnDescriptor.builder()
                .columnName(name)
                .jdbcType(Types.VARCHAR)
                .typeName("VARCHAR")
                .primarykey(primaryKey)
                .build();
    }

    private static JdbcSinkRecord toJdbcRecord(KafkaDebeziumSinkRecord record) {
        return new JdbcKafkaSinkRecord(
                record.getOriginalKafkaRecord(),
                config.getPrimaryKeyMode(),
                config.getPrimaryKeyFields(),
                config.getFieldFilter(),
                config.cloudEventsSchemaNamePattern(),
                dialect);
    }
}
