/*
 * Copyright Debezium Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package io.debezium.connector.jdbc.integration.snowflake;

import static org.fest.assertions.Assertions.assertThat;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.apache.kafka.connect.sink.SinkRecord;
import org.awaitility.Awaitility;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import io.debezium.bindings.kafka.KafkaDebeziumSinkRecord;
import io.debezium.connector.jdbc.JdbcSinkConnectorConfig;
import io.debezium.connector.jdbc.JdbcSinkConnectorTask;
import io.debezium.connector.jdbc.JdbcSinkTaskTestContext;
import io.debezium.connector.jdbc.junit.jupiter.snowflake.Sink;
import io.debezium.connector.jdbc.junit.jupiter.snowflake.SnowflakeSinkDatabaseContextProvider;
import io.debezium.connector.jdbc.util.DebeziumSinkRecordFactory;
import io.debezium.connector.jdbc.util.RandomTableNameGenerator;
import io.debezium.connector.jdbc.util.SinkRecordFactory;

/**
 * Integration tests that execute multi-value (multi-row) INSERT, MERGE and DELETE statements
 * against a real Snowflake instance, proving the SQL shapes generated by
 * {@code SnowflakeDatabaseDialect} are accepted by the server. Each test also checks the
 * Snowflake query history for a multi-tuple VALUES list, so a silent fallback to legacy
 * single-row JDBC batching fails the test rather than passing on identical table state.
 *
 * Requires the {@code SNOWFLAKE_*} environment variables documented in
 * {@link io.debezium.connector.jdbc.junit.jupiter.snowflake.AbstractSinkDatabaseContextProvider}.
 */
@Tag("all")
@Tag("e2e")
@Tag("e2e-snowflake")
@ExtendWith(SnowflakeSinkDatabaseContextProvider.class)
public class JdbcSinkMultiValueStatementsIT {

    private final Sink sink;
    private final SinkRecordFactory factory = new DebeziumSinkRecordFactory();
    private final RandomTableNameGenerator tableNameGenerator = new RandomTableNameGenerator();

    private final List<String> createdTables = new ArrayList<>();

    private JdbcSinkConnectorTask sinkTask;

    public JdbcSinkMultiValueStatementsIT(Sink sink) {
        this.sink = sink;
    }

    @AfterEach
    public void afterEach() throws Exception {
        if (sinkTask != null) {
            sinkTask.stop();
            sinkTask = null;
        }
        for (String tableName : createdTables) {
            sink.execute("DROP TABLE IF EXISTS " + sink.formatTableName(tableName));
        }
        createdTables.clear();
    }

    @Test
    public void testMultiValueInsertWritesAllRecordsInOneStatement() throws Exception {
        final String topicName = randomTopicName();
        startSinkTask(Map.of(JdbcSinkConnectorConfig.INSERT_MODE, "insert"));

        final List<KafkaDebeziumSinkRecord> records = new ArrayList<>();
        for (byte key = 1; key <= 3; key++) {
            records.add(factory.createRecord(topicName, key));
        }
        put(records);

        assertThat(queryIdToName(topicName)).isEqualTo(Map.of(1, "John Doe", 2, "John Doe", 3, "John Doe"));
        assertMultiValueStatementExecuted(topicName, "INSERT INTO");
    }

    @Test
    public void testMultiValueUpsertMergesReducedRecordsInOneStatement() throws Exception {
        final String topicName = randomTopicName();
        startSinkTask(Map.of(
                JdbcSinkConnectorConfig.INSERT_MODE, "upsert",
                JdbcSinkConnectorConfig.USE_REDUCTION_BUFFER, "true"));

        // Two keys in one flush; key 1 is reduced to its latest state before the multi-row MERGE
        put(List.of(
                factory.createRecord(topicName, (byte) 1),
                factory.createRecord(topicName, (byte) 2),
                factory.updateRecord(topicName)));

        assertThat(queryIdToName(topicName)).isEqualTo(Map.of(1, "Jane Doe", 2, "John Doe"));
        assertMultiValueStatementExecuted(topicName, "MERGE INTO");
    }

    @Test
    public void testMultiValueDeleteRemovesAllKeysInOneStatement() throws Exception {
        final String topicName = randomTopicName();
        startSinkTask(Map.of(
                JdbcSinkConnectorConfig.INSERT_MODE, "insert",
                JdbcSinkConnectorConfig.DELETE_ENABLED, "true"));

        put(List.of(
                factory.createRecord(topicName, (byte) 1),
                factory.createRecord(topicName, (byte) 2),
                factory.createRecord(topicName, (byte) 3)));
        assertThat(queryIdToName(topicName).keySet()).hasSize(3);

        // Both deletes land in the same flush and execute as a single multi-row DELETE
        put(List.of(
                factory.deleteRecord(topicName, (byte) 1),
                factory.deleteRecord(topicName, (byte) 3)));

        assertThat(queryIdToName(topicName)).isEqualTo(Map.of(2, "John Doe"));
        assertMultiValueStatementExecuted(topicName, "DELETE FROM");
    }

    private void startSinkTask(Map<String, String> properties) {
        final Map<String, String> config = new LinkedHashMap<>();
        config.put(JdbcSinkConnectorConfig.CONNECTION_URL, sink.getJdbcUrl());
        config.put(JdbcSinkConnectorConfig.CONNECTION_USER, sink.getUsername());
        config.put(JdbcSinkConnectorConfig.CONNECTION_PASSWORD, sink.getPassword());
        config.put("hibernate.dialect", "io.debezium.connector.jdbc.hibernate.dialect.snowflake.SnowflakeDialect");
        config.put(JdbcSinkConnectorConfig.SCHEMA_EVOLUTION, "basic");
        config.put(JdbcSinkConnectorConfig.PRIMARY_KEY_MODE, "record_key");
        config.put(JdbcSinkConnectorConfig.USE_MULTI_VALUE_STATEMENTS, "true");
        config.putAll(properties);

        sinkTask = new JdbcSinkConnectorTask();
        sinkTask.initialize(new JdbcSinkTaskTestContext(config));
        sinkTask.start(config);
    }

    private void put(List<KafkaDebeziumSinkRecord> records) {
        final List<SinkRecord> kafkaRecords = records.stream().map(KafkaDebeziumSinkRecord::getOriginalKafkaRecord).toList();
        sinkTask.put(kafkaRecords);
        if (sinkTask.getLastProcessingException() != null) {
            throw new RuntimeException("JDBC sink threw an exception processing the data", sinkTask.getLastProcessingException());
        }
    }

    private Map<Integer, String> queryIdToName(String tableName) throws SQLException {
        final Map<Integer, String> rows = new LinkedHashMap<>();
        try (Statement statement = sink.getConnection().createStatement();
                ResultSet rs = statement.executeQuery("SELECT id, name FROM " + sink.formatTableName(tableName) + " ORDER BY id")) {
            while (rs.next()) {
                rows.put(rs.getInt(1), rs.getString(2));
            }
        }
        return rows;
    }

    /**
     * Asserts that a statement with a multi-tuple {@code VALUES} list was executed against the
     * given table. The legacy JDBC batching path sends single-tuple statements only, so the
     * {@code "),("} fragment in the query text proves the multi-value path ran and did not fall
     * back. Query history is near real time, so the check polls briefly, retrying through
     * transient errors such as a warehouse resume. The history window is time-bounded so a busy
     * shared account cannot push the sink's statement beyond the result limit, and matching uses
     * {@code CONTAINS} rather than {@code LIKE} so the underscores in the table name cannot act
     * as wildcards.
     */
    private void assertMultiValueStatementExecuted(String tableName, String statementPrefix) {
        final String sql = "SELECT COUNT(*) FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY("
                + "END_TIME_RANGE_START => DATEADD('minute', -10, CURRENT_TIMESTAMP()), RESULT_LIMIT => 1000))"
                + " WHERE STARTSWITH(query_text, '" + statementPrefix + "')"
                + " AND CONTAINS(UPPER(query_text), '" + sink.formatTableName(tableName) + "')"
                + " AND CONTAINS(query_text, '),(')";
        Awaitility.await("Multi-value '" + statementPrefix + "' statement in query history for table " + tableName)
                .atMost(Duration.ofMinutes(1))
                .pollInterval(Duration.ofSeconds(2))
                .ignoreExceptions()
                .until(() -> {
                    try (Statement statement = sink.getConnection().createStatement();
                            ResultSet rs = statement.executeQuery(sql)) {
                        return rs.next() && rs.getInt(1) > 0;
                    }
                });
    }

    private String randomTopicName() {
        final String topicName = "multi_value_" + tableNameGenerator.randomName();
        createdTables.add(topicName);
        return topicName;
    }
}
